development:
  adapter: postgresql
  encoding: unicode
  database: lifti_development
  pool: 5
  username: kaichimomose
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lifti_test
  pool: 5
  username: kaichimomose
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: lifti_production
  pool: 5
  username: kaichimomose
  password:
